GerenPlaca/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))

    
]

core/urls.py
from django.urls import path

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.home, name='home'),
]

core/models.py
from django.db import models

# Create your models here.

placas/models.py
from django.db import models


class Lote(models.Model):
    id_lote  = models.AutoField(
        primary_key=True
        )
    
    lote_numero = models.CharField(
        max_length=10,
        unique=True
        )


class Modelo_placa(models.Model):
    id_modelo = models.AutoField(
        primary_key=True, 
       
        )

    descricao = models.CharField(
        max_length=50
        )
    
    tipo = models.CharField(
        'Tipo',
        max_length=30
        )
     
class Item(models.Model):
    id_item = models.AutoField(
        'ID_Item', 
        primary_key = True
        )

class Placa(models.Model):
    id_placa = models.AutoField(
        'ID_Placa',
        primary_key = True
        )

    id_modelo = models.ForeignKey(
        Modelo_placa,  on_delete=models.CASCADE, 
        )

    id_lote = models.ForeignKey(
        Lote,  on_delete=models.CASCADE
        )

    numero_serie = models.IntegerField(
        'Número de Série',
        unique=True,

        ) 

    processo = models.CharField(
        max_length=20
        )

    revisao_lm = models.IntegerField('Revisão LM'
        )

    class Meta:
        db_table = 'PLACAS'


    
       
    

core/views.py
from django.shortcuts import render


def home(request):
    context = {
        'titulo': 'H A U T Z'
    }
    return render(request, 'index.html', context)
    

placas/views.py
from django.shortcuts import render

# Create your views here.

core/templates/base.html
{% load static %}

<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <html lang="pt-br">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

  
    
    <title>Hautz - {% block titulo %}  {% endblock %} </title>
</head>


<body id="page-top">

   <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <a class="navbar-brand mr-1" href="{% url 'core:home' %}"><img src="" width="" alt= "Painel Adelco" /> </a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Pesquisar..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-4">  

      </li>
      <li class="nav-item dropdown no-arrow mx-1">
     

      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Configurações</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Sair</a>
        </div>
      </li>
    </ul>

  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:home' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Gerenciamento</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Placas:</h6>
          <a class="dropdown-item" href="admin/placas/placa/add/">Cadastro Placas</a>

          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Usuários:</h6>
          <a class="dropdown-item" href="admin/auth/user/add/">Cadastro Usuários</a>
        </div>
      </li>
      <!-- # botão graficos
        <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Gráficos</span></a>
      </li>
     -->

     <!-- # botão tabelas
       <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tabelas</span></a>
      </li>
    -->
    </ul>

    <div id="content-wrapper">

      <div class="container-fluid">

        <!-- Titulo-secundário -->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'core:home' %}">Home</a>
          </li>
          <li class="breadcrumb-item active">{% block titulo-secundario %} {% endblock  %}</li>
        </ol>

        <!-- Cards-->
        <div class="row">
          <div class="col-xl-4 col-sm-6 mb-3">
            <div class="card text-white bg-warning o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-list"></i>
                </div>
                <div class="mr-5">Tarefas</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">Ver detalhes</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-4 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">Estoque de placas</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">Ver detalhes</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
          <div class="col-xl-4 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
              <div class="card-body">
                <div class="card-body-icon">
                  <i class="fas fa-fw fa-life-ring"></i>
                </div>
                <div class="mr-5">Ordens de serviço!</div>
              </div>
              <a class="card-footer text-white clearfix small z-1" href="#">
                <span class="float-left">Ver detalhes</span>
                <span class="float-right">
                  <i class="fas fa-angle-right"></i>
                </span>
              </a>
            </div>
          </div>
        </div>
     
       
        {% block conteudo %}
        
        {% endblock conteudo %}
  
  
  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Deseja sair?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Clique em "Sair" se quiser encessar a sessão.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="login.html">Sair</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{%static 'static/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{%static 'js/sb-admin.min.js' %}"></script>

  <!-- Demo scripts for this page-->
  <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
 

    <footer>
        <hr/>
        <p class="text-center"> Todos os direitos reservados Hautz
    </footer>
</body>
</html>

core/templates/index.html
{% extends "base.html" %}

{% block titulo %} Dashboard{% endblock  %}
{% block titulo-secundario %} Dashboard{% endblock  %}

{% block conteudo %}
<!-- Area Chart Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-chart-area"></i>
            Volume de Placas</div>
          <div class="card-body">
            <canvas id="myAreaChart" width="100%" height="30"></canvas>
          </div>
          <div class="card-footer small text-muted">Atualizado em 01/01/2000 00:00</div>
        </div> 

        <!-- DataTables Example -->
        <div class="card mb-3">
          <div class="card-header">
            <i class="fas fa-table"></i>
            Testes</div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Id</th>
                    <th>Placa</th>
                    <th>Teste 1</th>
                    <th>Teste 2</th>
                    <th>Teste 3</th>
                    <th>Teste Final</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Id</th>
                    <th>Placa</th>
                    <th>Teste 1</th>
                    <th>Teste 2</th>
                    <th>Teste 3</th>
                    <th>Teste Final</th>
                  </tr>
                </tfoot>
                <tbody>
                  <tr>
                    <td>NULL</td>
                    <td>NULL</td>
                    <td>NULL</td>
                    <td>NULL</td>
                    <td>NULL</td>
                    <td>NULL</td>
                  </tr>

                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="card-footer small text-muted">Atualizado em 01/01/2000 00:00</div>
        </div>

      </div>
      <!-- /.container-fluid -->

    </div>
    <!-- /.content-wrapper -->
{% endblock conteudo %}